### ISSUE TITLE
Feature request: Bigger initial fontsize

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-issues#10]
Ok, getting into the small issues now..

The first time I tried to add a message on the screen it started out with a tiny font.
Is it possible to set the initial font size bigger? If posible relative to captured screen size. 
On a 1920x1080 screen a decent fontsize would be around 30.

![Initial Fontsize](https://user-images.githubusercontent.com/53835804/91968813-7e764e00-ed15-11ea-85ac-7f219891434d.png)

Once set to 30 the next message I add has that size set already, it's only tiny the first time, so it's only a small usability improvement.

**Comment by satishsampath** [comment]
I'll adjust the default text size to be based on the screen scaling/DPI. Based on my calculations, it may never be something like 30, but higher than 8.
@dark-passages , may I ask what is your screen scaling/DPI setting?

**Comment by dark-passages** [comment]
The screen of my laptop is 1920x1080 on a 40cm screen. So high resolution on a relative small screen.

(I'm one of those people that prefer to do everything in full screen windows, preferably 2 screens, unlike some of my collegues that love to see all apps on the screen at the same time in tiny windows.)
