### ISSUE TITLE
Double menu

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-issues#11]
The Wink icon shows in the title bar and also as the first menu item.

![Double menu](https://user-images.githubusercontent.com/53835804/91969311-2d1a8e80-ed16-11ea-918a-d381d0921ab3.png)

This is not normal for windows applications, is this done on purpose?

**Comment by satishsampath** [comment]
The second icon is necessary to minimize/close/maximize the inner project window. But, I'll change the inner icon so it is clearer.

**Comment by dark-passages** [comment]
So there is a reason, then it's ok, was just wondering.
Looks a little different now.
