### ISSUE TITLE
Input driven capture is strange on Windows 10

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-issues#12]
I have windows 10 installed and when I use Wink Input drive capture on my screen it does the folowing:

In any browser: No frames are captured
In Microsoft Outlook (the only app where version 2.0 could work): It now makes continuous screenshots.
In Microsoft Word (version 2.0 did not work here): It now makes continuous screenshots.

So for the apps that can be captured it uses timed screenshots but most apps can not be captured yet. (unless I press the Timed capture button manualy)

Also: I tried to use the "Use timed capture when mouse button is down" option in paint.net but it does not capture any frames, only when I select "Start timed capture" it captures frames, but regardless of mouse button status.

**Comment by satishsampath** [comment]
@dark-passages , I wonder if all of the apps you mention are 64-bit apps and hence Wink can't do input driven capture.. may be you can try a few 32-bit apps and a few 64-bit apps, to confirm this theory? I'll do the same

**Comment by dark-passages** [comment]
It is possible they are 64-bit apps, I'll check if I have some 32-bit apps.

**Comment by dark-passages** [comment]
I found the Arduino app in the Programs x86 folder so that should be 32-bits. 
When I start Input driven capture it does the same thing: continuous screenshots.

While taking all the screenshots I tried to open a menu and nothing happened.

![Menu 1](https://user-images.githubusercontent.com/53835804/92231296-d3989800-eeac-11ea-9543-a062e929b442.png)

Then when I move my mouse down some of the options from the menu appear (because of mouse over effect).

![Menu 2](https://user-images.githubusercontent.com/53835804/92231300-d4312e80-eeac-11ea-9bd7-071ce65b7090.png)

Without Wink making all the screenshots the menu appears normal:

![Menu 3](https://user-images.githubusercontent.com/53835804/92231301-d4312e80-eeac-11ea-8f56-d6216d5b45c7.png)


I also tried the Touch portal app (32-bit) but no screenshots were taken. 

In Basecamp the continuous screenshots were used, this also made it dificult for the app to show the menu. Unlike the Adruino app the whole menu is drawn every time so once I moved my cursor down the whole menu appeared. (I removed all the screenshots where there was only a cursor move, saving more than 300 screenshots in space.)

[Basecamp.zip](https://github.com/satishsampath/wink-issues/files/5174427/Basecamp.zip)

**Comment by satishsampath** [comment]
Fixed in build 2.506. Please test and confirm, if it's still happening reopen this issue.

**Comment by dark-passages** [comment]
NICE! 
It works on 32-bit apps and on 64-bit apps! 
That is: Mouse click works even in my Chrome browser, but typing does not trigger a screenshot yet.

**Comment by dark-passages** [comment]
**Update:** Sometimes typing does trigger a screenshot.
I'm not sure why it did not work in my first test or why it does work in my second test. 
Will try some more to see if I can find a pattern.
