### ISSUE TITLE
Unable to Use Input-Driven Capture

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-issues#17]
I am unable to capture any frames on Input-Driven Capture mode. Timed and Screenshot work.

I am running Windows 10 Home edition 64 bit on an HP 15 laptop with 6 GB of RAM.

**Comment by satishsampath** [comment]
Do you think this is the same issue as #12 ?

**Comment by t-rains** [comment]
Yes, it may be except I have not found any way to produce Input-Driven capture. I did try with Outlook and Word, also Chrome
 and the Desktop.

**Comment by satishsampath** [comment]
Fixed in build 2.506. Please test and confirm, if it's still happening reopen this issue.

**Comment by t-rains** [comment]
Input-driven capture is still not functioning correctly. 

  - Keystrokes are not triggering the capture.
  - Mouse clicks only trigger captures on OS events such as clicking in the taskbar or changing windows (which I could not do before when no mouse clicks would trigger).

I also keep getting the 'New Version' message even though I uninstalled older builds before installing 2.506.

**Comment by satishsampath** [comment]
Can you please give specific steps to reproduce the mouse issues?
- which application are you trying to capture? Chrome browser or something
else?
- which parts work and which ones don't?

**Comment by t-rains** [comment]
Using the Chrome browser trying to capture document development in Word 2013, including typing and formatting. None of the typing (including changing to the Insert ribbon to add a symbol and back) was captured and none of the formatting (font color, boldness, italics, underlining) was captured. Clicking on the taskbar and changing windows to the Chrome browser were the only events that triggered. I am using an HP 15 laptop so “moussing” is done on the touchpad for now.
