### ISSUE TITLE
Resize of textbox

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-issues#18]
I added a textbox to see the new resize handles (Thanks for making them bigger) 

![Scaling 1](https://user-images.githubusercontent.com/53835804/92226969-d6dc5580-eea5-11ea-8de4-b301fc9cc930.png)

To remove the large amount of space below the text I tried to make the box a bit lower, but then this happened:

![Scaling 2](https://user-images.githubusercontent.com/53835804/92226973-d774ec00-eea5-11ea-8b76-6c03ca1892c3.png)

I only draged the middle handle at the top down, I did not resize the textbox in with. it becomes narrow on it's own, after dragging the handle back up the with returns to the correct size again.

**Comment by satishsampath** [comment]
Yes, this is a known issue. If you make the callouts (i.e. textboxes) smaller than their minimum size, it starts getting squished. I don't have a fix, instead my suggestion will be to make it slightly larger so this doesn't happen.
