### ISSUE TITLE
Capture now

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-issues#19]
When I use the mouse to capture the screen the "Capture now" text is visible in the captured screen.

![Capture now](https://user-images.githubusercontent.com/53835804/92230529-9253b880-eeab-11ea-8536-a75d28abef86.png)

**Comment by satishsampath** [comment]
I got a repro case, fix ready.

**Comment by satishsampath** [comment]
Released in beta build 2.504. Please try and confirm if it works.

**Comment by dark-passages** [comment]
Yes it works now.
The menu disapears instantly, the blue bar fades slowly and now Wink waits long enough to take the screenshot for it to be gone.
