### ISSUE TITLE
Captured video is rendered as mirrored

### ISSUE THREAD

**Issue by svatas** [satishsampath/wink-issues#2]
After I started video capturing the result is video file which is mirrored...

See attached file : 
[wink-beta2.zip](https://github.com/satishsampath/wink-issues/files/5135419/wink-beta2.zip)

**Comment by satishsampath** [comment]
Found and fixed the bug.. will close this issue once the next build is released. Thanks.

**Comment by satishsampath** [comment]
Posted in the beta group about latest build with fix, so closing.
