### ISSUE TITLE
Shapes background 

### ISSUE THREAD

**Issue by Antonello-coder** [satishsampath/wink-issues#20]
Setting the background color of the shapes doesn't work, it renders transparent.

**Comment by satishsampath** [comment]
Can you give more details, such as which OS you are using and how (which dialog, which UI menu etc) you are setting the background color of the shape?

**Comment by Antonello-coder** [comment]
OS is Win10 Pro. I set the backgroud using the controls on the right, the opaque is 100% but the rect remains transparent in the editor and in the mp4.

![immagine](https://user-images.githubusercontent.com/66787739/92300547-2e3cfd00-ef5c-11ea-8ec1-6657f8747e2a.png)

**Comment by satishsampath** [comment]
Can you also show a screenshot of the shape selection dialog i.e. the 'Choose Preset Shape' dialog, with your shape selected?

**Comment by satishsampath** [comment]
I think I know what's happening. Is this a Wink 2.0 project that you just opened in the new beta version?

**Comment by satishsampath** [comment]
Found the issue, will be fixed in next beta release

**Comment by satishsampath** [comment]
Released in beta build 2.504. Please try and confirm if it works.

**Comment by Antonello-coder** [comment]
I was out for a little holiday. Yes, to confirm you assertion, I'm converting some Wink 2.0 projects. Thanks.
