### ISSUE TITLE
Buttons 

### ISSUE THREAD

**Issue by Antonello-coder** [satishsampath/wink-issues#21]
Clicking a button doesn't jump to the expected frame

**Comment by satishsampath** [comment]
Can you give more details?
- Is this happening within Wink, or in the rendered video when viewing in the browser?
- If it's in a browser, which browser and which operating system?

**Comment by Antonello-coder** [comment]
Happens in the rendered, using Firefox 80 Win 10.
In MS Edge is OK.

**Comment by satishsampath** [comment]
Looks like this is the same issue as #6 , so I'm closing as duplicate. Please reopen if you don't think so.
