### ISSUE TITLE
Wink does not appear on the main screen

### ISSUE THREAD

**Issue by vivonslasieste** [satishsampath/wink-issues#22]
(low severity)
If you use wink on a secondary screen then you close Windows without stopping Wink first.
If you restart windows and wink without the second screen, then Wink is open but invisible, it is on the second screen that does not exist.

**Comment by satishsampath** [comment]
Fix will be ready in the next beta release.

**Comment by satishsampath** [comment]
Fixed in beta build 2.505. Please check and if the issue still exists, reopen this issue.
