### ISSUE TITLE
Launch of Wink tutorials.

### ISSUE THREAD

**Issue by ManiglierE** [satishsampath/wink-issues#23]
Hello Satish
Well done for your work.
I wanted to create a tutorial without a scroll bar, with a button on the first image to move on.
I noticed that we cannot start the tutorial without starting the video playback. The button for the next image is not active until playback is started.
I have the same problem with other tutorials having the scroll bar, you must start with the play button.
Once the tutorial is in reading mode, if we go back to the first image, the next page button works normally.
In addition, I would also like to be able to use the scroll bar to move the cursor.
Cordially.
Eric

**Comment by satishsampath** [comment]
I'm adding a "click to play" screen on top of the video, so user first has to click that and it'll start the playback. Please test that and see if it works as expected.

**Comment by satishsampath** [comment]
Fix will be available in the next beta build.

**Comment by satishsampath** [comment]
Fixed in beta build 2.505. Please check and if the issue still exists, reopen this issue.
