### ISSUE TITLE
Viewing translations

### ISSUE THREAD

**Issue by ManiglierE** [satishsampath/wink-issues#24]
I use Wink in French.
On version 503, you can no longer change languages.
On versions 500, 501 and 502, some translations displayed the name of the variable and not the translation.
![Wink3 0 290-02](https://user-images.githubusercontent.com/66283878/92327559-cb7e5b00-f05a-11ea-84f3-e138e6cde252.jpg)
![Wink3 0 290-05Fr](https://user-images.githubusercontent.com/66283878/92327574-ddf89480-f05a-11ea-87b3-ce6c8917824e.jpg)
![Wink3 0 2501-06Fr](https://user-images.githubusercontent.com/66283878/92327591-06808e80-f05b-11ea-8c88-35665296ab2e.jpg)

**Comment by satishsampath** [comment]
> On version 503, you can no longer change languages.
In build 503, what do you see in the "File > Choose Language" menu? It should list all the languages to choose. Is that not working?

> On versions 500, 501 and 502, some translations displayed the name of the variable and not the translation.
That's correct, these are new strings added recently and haven't been translated to any language other than English yet. I'll ask for your help with translating these strings before release.

**Comment by satishsampath** [comment]
I was able to reproduce. Fix will be ready in the next beta release.

**Comment by satishsampath** [comment]
Fixed in beta build 2.505. Please check and if the issue still exists, reopen this issue.
