### ISSUE TITLE
New version available?

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-issues#25]
I got some updates for the new version now, but version 2.504 and 2.505 tell me there is a newer version available after I installed the latest version. I guess the checking of the versionnumbers is not working properly.

**Comment by satishsampath** [comment]
Does this happen even with version 2.505? 
If yes, can you show screenshots of the Help>About dialog ?
Also, please confirm if you see the 'new version available' message only once or every time you start Wink

**Comment by satishsampath** [comment]
Ah, found the issue and fix will be there in the next build.

**Comment by dark-passages** [comment]
Every time I start Wink the folowing popup apears:
![Newversion](https://user-images.githubusercontent.com/53835804/92570031-a7509300-f281-11ea-9e23-2ac8b24e2708.png)

As requested the About window:
![Newversion about](https://user-images.githubusercontent.com/53835804/92570034-a7e92980-f281-11ea-8d9e-317c3c4022ff.png)

**Comment by satishsampath** [comment]
Fixed in 2.507, please test and confirm if it works. If not, please reopen this issue.
