### ISSUE TITLE
control bar and video

### ISSUE THREAD

**Issue by theodegeais** [satishsampath/wink-issues#27]
wink 2.506
is there a way to adjust video with control bar ?
tested in google chrome, firefox, IE (i think it's browser's independant)
on linux mint and win10 64 bit. Even when the video is played from a web site
Impossible to forward or rewind the video to a spécifical time with control bar.

**Comment by satishsampath** [comment]
Will be ready in the next beta build.

**Comment by satishsampath** [comment]
Fixed in 2.507, please test and confirm if it works. If not, please reopen this issue.

**Comment by theodegeais** [comment]
wink 2.507 control bar with video OK. Playing video tested in google chrome win10_64 > OK. Playing video on linux mint on  Firefox OK
Thanks a lot
