### ISSUE TITLE
input driven capture Keyboard doesn't work

### ISSUE THREAD

**Issue by theodegeais** [satishsampath/wink-issues#28]
wink 2.506
input driven capture (key press) doesn't work when start input driven capture.
i select it (key press) and deselect and re select it and not operating.
tested on wink 2.506 on win10_64

**Comment by satishsampath** [comment]
Does mouse move/click capture properly when this happens?

**Comment by theodegeais** [comment]
Clicks are ok (frames taken by wink). If i move the cursor and click again (frames are taken too, no problem)
But during a drag and drop : 1) frames are taken on the click . 2) during the move, no frames (Use of timed capture When Mouse Button Is Down is checked). 3) frames are taken when i release the click.
When creating the video the movements of mouse cursors are ok 
I'm on win10_64 the programs was Libreoffice (64) and on the windows 10 desktop. Keyboard strokes doesn't create frames in wink (even Enter...).

**Comment by satishsampath** [comment]
Fix ready in the next beta build

**Comment by satishsampath** [comment]
Fixed in 2.507, please test and confirm if it works. If not, please reopen this issue.

**Comment by theodegeais** [comment]
Tested wink 5.07 (win10_64) key press in input driven OK.
Thanks
