### ISSUE TITLE
Input-driven capture is still not functioning correctly.

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-issues#29]
Input-driven capture is still not functioning correctly. 

  - Keystrokes are not triggering the capture.
  - Mouse clicks only trigger captures on OS events such as clicking in the taskbar or changing windows (which I could not do before when no mouse clicks would trigger).

I also keep getting the 'New Version' message even though I uninstalled older builds before installing 2.506.

_Originally posted by @t-rains in https://github.com/satishsampath/wink-issues/issues/17#issuecomment-689850306_

**Comment by t-rains** [comment]
P.S. - Mouse movements are not recorded at all for me in Input-Driven Capture. (I actually have not tested it in other input modes yet.)

**Comment by t-rains** [comment]
P.S. - I do have mouse movements in Timed and Manual Snapshot Capture modes, Still not seen in Input-Driven Capture.

**Comment by satishsampath** [comment]
Same as #28
