### ISSUE TITLE
change the installation folder

### ISSUE THREAD

**Issue by vivonslasieste** [satishsampath/wink-issues#3]
Hello,

Thank you very much for this first version.

I wished to install this beta version in a different folder so as not to lose the old version of wink.

When I generate an animation from an old project (.wnk) with new version it looks for some files in the old installation but doesn't open them even though they exist.

![error](https://user-images.githubusercontent.com/70328086/91447112-957df180-e878-11ea-95e5-a213f7e1f3cc.png)

Cordially

**Comment by satishsampath** [comment]
Which directory did you install the beta build in?
You can also probably change the preloader in your copied project to a Wink 3.0 preloader, in the Project > Settings dialog. Please check if that works.

**Comment by vivonslasieste** [comment]
Install directory :

C:\Program Files (x86)\DebugMode\winkbeta\Wink

 

I choose “French”

 

In the menu “Projet – Option” I can’t see how to change the preloader.

 



 

Thank you for your work and your reactivity.

 

François Thiberville

 

De : Satish Sampath <notifications@github.com> 
Envoyé : jeudi 27 août 2020 16:03
À : satishsampath/wink-issues <wink-issues@noreply.github.com>
Cc : vivonslasieste <vivonslasieste@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [satishsampath/wink-issues] change the installation folder (#3)

 

Which directory did you install the beta build in?
You can also probably change the preloader in your copied project to a Wink 3.0 preloader, in the Project > Settings dialog. Please check if that works.

**Comment by satishsampath** [comment]
I'm sorry, I wrote the wrong word.
In "Project > Settings" dialog, please choose a "control bar" that ships with Wink 3.0. For example, see this attached picture.
1) Click the "Choose" button
2) In the Choose ControlBar dialog, select any of the control bars listed
3) Click OK to close the dialog, then OK to close the other dialog.
4) Render the project, see if that works.
![Capture](https://user-images.githubusercontent.com/2305978/91525167-bdd81100-e8b5-11ea-89e5-7464222757a2.PNG)

**Comment by vivonslasieste** [comment]
Hi

Thank you, I followed your instructions to choose "rounded-green" and then I chose "project - render".

 

Here is the result:

(I checked twice that the directory exists and my path to ffmpeg is good in “file – preferences”)

 

 



 



 

 

François

 

 

De : Satish Sampath <notifications@github.com> 
Envoyé : vendredi 28 août 2020 07:38
À : satishsampath/wink-issues <wink-issues@noreply.github.com>
Cc : vivonslasieste <vivonslasieste@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [satishsampath/wink-issues] change the installation folder (#3)

 

I'm sorry, I wrote the wrong word.
In "Project > Settings" dialog, please choose a "control bar" that ships with Wink 3.0. For example, see this attached picture.

1.	Click the "Choose" button
2.	In the Choose ControlBar dialog, select any of the control bars listed
3.	Click OK to close the dialog, then OK to close the other dialog.
4.	Render the project, see if that works.
 <https://user-images.githubusercontent.com/2305978/91525167-bdd81100-e8b5-11ea-89e5-7464222757a2.PNG>

**Comment by satishsampath** [comment]
Hi François, Your reply doesn't have the actual error message or image. Can you please check above and add the relevant information? Thanks. Satish

**Comment by satishsampath** [comment]
Fixed the original issue reported first in here, so closing now.
