### ISSUE TITLE
Shapes Background 2

### ISSUE THREAD

**Issue by Antonello-coder** [satishsampath/wink-issues#30]
Hello, I'm sorry but the issue still exists opening old 2.0 projects, here some screenshots. Thanks
![immagine](https://user-images.githubusercontent.com/66787739/92759172-bd4c7980-f38f-11ea-89fe-a20bca7b5e9b.png)
![immagine](https://user-images.githubusercontent.com/66787739/92759292-de14cf00-f38f-11ea-9271-7859ec7f2740.png)

**Comment by satishsampath** [comment]
Can you check what the name of the shape you used for this project, by opening the project in Wink 2.0? I have a feeling that it was a custom/new shape you've created in your computer, and Wink 3.0 doesn't know about it.. hence showing a blank shape instead.

**Comment by Antonello-coder** [comment]
Since the projects were made by another person than me and I din't know about this feature and yes, I confirm they are custom shapes. 
Is there e trick to export them to Wink 3.0?

**Comment by Antonello-coder** [comment]
Found it! But in wink 3.0 the colors are different. Here an example:
![Immagine](https://user-images.githubusercontent.com/66787739/93050755-bb223d80-f663-11ea-9f8e-eceb06273ea0.png)
![Untitled 1](https://user-images.githubusercontent.com/66787739/93050763-be1d2e00-f663-11ea-8cca-cd35dd1a0059.png)

**Comment by satishsampath** [comment]
Looks like the shape color details are screwed up. Any chance you can attach your .wnk project to this github issue? I can debug what's going on

**Comment by Antonello-coder** [comment]
Into the zip there is a reduced copy of the project (2 frames)+the custom shapes files. 
Thanks
[test.zip](https://github.com/satishsampath/wink-issues/files/5219174/test.zip)

**Comment by satishsampath** [comment]
Looks like you've saved this using Wink beta. Can you instead send me a project saved by Wink 2.0? Looks like the error is in loading the old format project and the shape colors are mixed up.

**Comment by Antonello-coder** [comment]
Sorry for the mistake, here's the project saved with 2.0
[test.zip](https://github.com/satishsampath/wink-issues/files/5220547/test.zip)

**Comment by satishsampath** [comment]
Thanks, this helped. Fix is ready and will be out in the next build. I've also added a warning that shows on screen if a callout or shape cannot be loaded when opening a project.

**Comment by Antonello-coder** [comment]
thanks

**Comment by satishsampath** [comment]
Fixed in release candidate build 2.508
