### ISSUE TITLE
Feature request: Ability to Edit and/or Create Custom Click-To-Play Screen

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-issues#32]
Will it be possible to edit and/or create custom Click-to-Play screens? I know the playoverlay.png is the image but the ability to change the hotspot size, shape, and location would be helpful for interactive simulations.

**Comment by satishsampath** [comment]
Of course. You can replace the image with any image you want. There is no hotspot, user can click anywhere on that image or other grayed out parts of the video and it starts playing. So once you render the video, just replace that image and you are all set :)

**Comment by t-rains** [comment]
Great! Thanks!
