### ISSUE TITLE
Cannot load shape

### ISSUE THREAD

**Issue by vivonslasieste** [satishsampath/wink-issues#33]
hi

Version 2.508
When opening a .wnk file I get the error message "cannot load shape".

This is the first time I get this message.
I didn't have this problem with previous versions with the same .wnk file but I didn't test versions 2.507 and 2.506 (sorry, I had too much work).

**Comment by vivonslasieste** [comment]
This message did not prevent me from producing a correct mp4 in which I did not see the slightest defect.
So I guess this message is not a serious bug!

**Comment by satishsampath** [comment]
This is a message I added in the new build, because it was silently failing to load shapes earlier.
Did it show the name of the shape that couldn't be loaded? I suspect that shape was something created in Wink 2.0 but not imported to Wink 3.0 yet.

**Comment by vivonslasieste** [comment]
No.
No name.

Le dim. 20 sept. 2020 à 19:20, Satish Sampath <notifications@github.com> a
écrit :

**Comment by satishsampath** [comment]
Interesting.
Can you please attach the .wnk project to this github issue? I can take a look.

**Comment by vivonslasieste** [comment]
You will find the file here ...

https://filez.agro-bordeaux.fr/opuu

**Comment by satishsampath** [comment]
Thanks. It looks like in frame 12, there is a shape without any proper name. So it is just a transparent rectangle. I opened in Wink 2.0 and it's the same there, just that there was no error message in Wink 2.0. In Wink 3.0, we now have an error message. You can remove that shape in frame 12 and that will remove the error from popping up again.

**Comment by vivonslasieste** [comment]
Thanks

 

De : Satish Sampath <notifications@github.com> 
Envoyé : dimanche 20 septembre 2020 21:10
À : satishsampath/wink-issues <wink-issues@noreply.github.com>
Cc : vivonslasieste <vivonslasieste@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [satishsampath/wink-issues] Cannot load shape (#33)

 

Thanks. It looks like in frame 12, there is a shape without any proper name. So it is just a transparent rectangle. I opened in Wink 2.0 and it's the same there, just that there was no error message in Wink 2.0. In Wink 3.0, we now have an error message. You can remove that shape in frame 12 and that will remove the error from popping up again.
