### ISSUE TITLE
Slow rendered playback

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-issues#34]
@t-rains Thanks for adding me to the drive folder. After looking at the videos, I think I understand the issue. 

Basically, you are using timed capture to take screenshots. Depending on what output frame rate you set, the output video can be either slow or fast. For example, the file "Timed Capture - 01f01r.wnk" shows a 1 frame/second capture and when rendered it shows each frame for 1 second as you would expect. But, the file "Timed Capture - 04f04r.wnk" was captured with almost 4 frames/second (sometimes 3, sometimes 5 etc).. and each frame actually shows up for 1 second in the output. Hence, the output video looks quite slow.

Is that correct? 

If yes, I think the fix is to also capture the time difference between each 'timed capture' frame so that it is set as the value for "Stay in this frame for ___ sec" for that frame. Then, when you render the video will show it for the correct amount of time.

_Originally posted by @satishsampath in https://github.com/satishsampath/wink-issues/issues/16#issuecomment-692215009_

**Comment by satishsampath** [comment]
@t-rains did you mean to open this issue? Looks like the text is just my previous comment :)

**Comment by t-rains** [comment]
Yes, had to leave for an emergency but will complete the comment tonight.

**Comment by t-rains** [comment]
The playback speed in Timed-Capture mode is much improved, thank you. It is non-linear (see 'Timed Clock Test - 20c20r Update' in the Google Drive) which is not critical for most operations and may be a function of my current system processing power. However, manual typing (or Input-Driven Capture typing) still has the slow ~ 1 second/frame timing (see 'Playback Speed Test 2 Update'). The playback speed does not change with different capture and render rate combinations. I don't see a workaround for typing but otherwise the update is great so far.

**Comment by satishsampath** [comment]
Ah ok. Do you think input-driven capture should preserve the timing of when frames are taken, so that the video matches the speed of capture? I think that somewhat makes sense, but want to confirm if that's what you are suggesting.

**Comment by t-rains** [comment]
Yes, if that is possible. Ideally, I would like to be able to control the frame rate of manual captures using 'Stay in Frame' timing and capture and render rate combinations. Examples would be for realistic portrayal of data entry or for animation of shapes. This was possible to do in Wink 2.0 but the switch to the superior .mp4 format may be the block. That I don't know.

**Comment by satishsampath** [comment]
Fixed in build 3.0

**Comment by t-rains** [comment]
This works smashingly now. Thank you.
