### ISSUE TITLE
Nonfunctioning buttons using smartphone

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-issues#36]
On my iPhone, the .mp4 runs continuously without stopping at the buttons that flash by. In a browser on my computer, you have HTML calls for the Wink player, control bars, javascript, and CSS. Is there a way to do that or something similar on a smartphone.

**Comment by satishsampath** [comment]
If you open the .mp4 on any device, phone or computer, it will play like a regular video without stopping. The only way is to open the HTML file on your phone as well. This is by design, because videos can't have interactivity as is. It's the HTML/CSS/JS that gives interactivity.

**Comment by t-rains** [comment]
Thanks for the confirmation.
