### ISSUE TITLE
Double click to .wnk does not work properly

### ISSUE THREAD

**Issue by svatas** [satishsampath/wink-issues#4]
When I start Wink and open e.g. sample project from SAMPLES folder, it is opened properly. When I try to open the same file via double mouse click in File Explorer, I will get this error message : 

![image](https://user-images.githubusercontent.com/2070628/91539989-78016400-e91a-11ea-98c5-ab1d660baf31.png)

When I do the same via click right mouse button and choose open from the menu I will got another error message : 

![image](https://user-images.githubusercontent.com/2070628/91540275-d9c1ce00-e91a-11ea-84d3-9fb3f59f289d.png)

after clicking to Continue I got : 

![image](https://user-images.githubusercontent.com/2070628/91540344-f5c56f80-e91a-11ea-9c88-86e8bb15b948.png)

I have Windows 10 

![image](https://user-images.githubusercontent.com/2070628/91540502-2c9b8580-e91b-11ea-9612-398a5d490782.png)

(Sorry, Czech language version but I think you will understand...)

**Comment by satishsampath** [comment]
Found and fixed the bug.. will close this issue once the next build is released. Thanks.

**Comment by satishsampath** [comment]
Posted in the beta group about latest build with fix, so closing.
