### ISSUE TITLE
bad position of the cursor in the wnk file

### ISSUE THREAD

**Issue by vivonslasieste** [satishsampath/wink-issues#5]
There is a bug in the display of the frame numbers related to the operation of the cursor placed below : 
the cursor must be in the middle of the screen so that you can see image 1.
You have to move it to the left to see the last frame.
it's not very serious but a little surprising
![Annotation 2020-09-02 085604](https://user-images.githubusercontent.com/70328086/91941835-30078600-ecfa-11ea-9856-2ee5bf4953f6.png)

**Comment by satishsampath** [comment]
Is there any particular thing that makes this happen? For example
1) are you seeing this for every project you open?
2) does this happen only when you create a new project from scratch?
3) does this happen only when you resize the window?
4) does this happen only when you change screen resolution?

**Comment by vivonslasieste** [comment]
I opened 3 of my old .wnk files; all have the same problem.
On frame 1, the cursor is in the middle.
If I push the cursor all the way to the right, I go to frame 373.
If I want to see the following frames I have to send the cursor to the left (more to the left than in the middle).

The problem appears as soon as I open the window, right away, before any manipulation.

**Comment by vivonslasieste** [comment]
I also encounter the problem on a new project

**Comment by satishsampath** [comment]
Ok thanks. Does this happen to the sample projects that come with Wink, such as sample.wnk/tutorial1.wnk/tutorial2.wnk (under the Wink install dir > Samples dir), or does this happen only to projects you record?

**Comment by satishsampath** [comment]
Also, can I ask what's your monitor/display resolution?

**Comment by vivonslasieste** [comment]
hi
I open tutorial1.wnk.
The cursor is well positioned but the file contains less than 373 frames.
I copy all the frames and duplicate them to get 412 frames.
I have again the malfunction: When the cursor is on the far right, I'm on frame 373.
I have to push the cursor to the left to see frames 374 and following.

I have 2 screens :
- the screen of my laptop 1920*1080 with the Windows setting 125%.
- an additional screen 1920*1080 set at 100%.
Wink is displayed on this screen

**Comment by vivonslasieste** [comment]
Sorry, I closed the subject with a clumsy click.
I reopen it.

I just passed my 2 screens at 100%.
I reboot Windows and open the previously created .wnk tutorial.
The problem is still there.
It seems to me that it happens as soon as the .wnk has more than 373 frames.

**Comment by satishsampath** [comment]
Thank you! The magic number of 373 frames was super useful. I found the issue and a fix is ready, will be there in the next update.

**Comment by vivonslasieste** [comment]
Great !

Maybe one day, for the fun, you’ll explain me why this famous 373 is so magic !

 

It is I who thank you for your work which will allow me not to waste tens of hours reconstructing documents.

 

François

 

De : Satish Sampath <notifications@github.com> 
Envoyé : samedi 5 septembre 2020 08:48
À : satishsampath/wink-issues <wink-issues@noreply.github.com>
Cc : vivonslasieste <vivonslasieste@gmail.com>; State change <state_change@noreply.github.com>
Objet : Re: [satishsampath/wink-issues] bad position of the cursor in the wnk file (#5)

 

Thank you! The magic number of 373 frames was super useful. I found the issue and a fix is ready, will be there in the next update.

**Comment by satishsampath** [comment]
Released in beta build 2.504. Please try and confirm if it works.
