### ISSUE TITLE
mp4 viewing does not stop on the right frame

### ISSUE THREAD

**Issue by vivonslasieste** [satishsampath/wink-issues#6]
I placed in my wnk file several buttons to force the video to stop.
You have to click on them to restart the video.
The rendering provides an mp4 file that does not stop each time on the frame where the button is located. (on some, it works, not on others, it seems random).

Sometimes, the mp4 stops on the next frame.
As a consequence : 
- the button is not visible to restart.
- the text near the button is not visible to my students.

![Annotation 2020-09-02 02](https://user-images.githubusercontent.com/70328086/91943080-46aedc80-ecfc-11ea-8be6-c624ac3ab216.png)

**Comment by svatas** [comment]
My investigation : 
- it is working in Google Chrome ( 85.0.4183.83) and Microsoft Edge ( 84.0.522.52) and Microsoft Edge Canary (87.0.627.0)
- not working in Firefox (80.0.1), Internet Explorer (11.450.1904.1.0) and Vivaldi (3.3.2022.26)
- test project is here [eee.zip](https://github.com/satishsampath/wink-issues/files/5162170/eee.zip)
- sometimes I can see the screen with inserted SVG objects just before the video stops, but then there is just screen without it, but stopped

**Comment by satishsampath** [comment]
@vivonslasieste , can you please
1) attach your project as well, so I can test with that
2) tell us what browser & version you used to test, so we can use the same

**Comment by vivonslasieste** [comment]
hi
The file .wnk is to big for github.
You can find it at : https://filez.agro-bordeaux.fr/xj8w3

I procced to the test mostly with : project - view rendered output in Wink
but also with Firefox and Edge (latest version).

My Windows 10 is up to date.

The problem of stopping on the wrong frame does not occur every time you switch to a frame with a button.

I haven't yet established if it always happens on the same button or if it's random.

However, i believe that when it happens, the MP4 stops on the frame immediately after the one containing the button.

**Comment by vivonslasieste** [comment]
I had the problem with 20 frames/s

I set to 10 frames/s and all the buttons are visible and work.

I test this inside the “view render output” of wink.

**Comment by satishsampath** [comment]
Ok, thanks. When you set it to 20 frames/s, does the issue happen on both Firefox and Edge, or only in one of them?

**Comment by vivonslasieste** [comment]
When i set it to 20 frames/s,  the issue happen on both Firefox, chrome and Edge.
When i set it to 10 frames/s,  the issue does not happen on both Firefox, chrome and Edge.

**Comment by satishsampath** [comment]
Thank you. I found the issue and a fix will be in the next beta release.

**Comment by satishsampath** [comment]
Released in beta build 2.504

**Comment by vivonslasieste** [comment]
Stop on the button "next slide".

Sorry, it doesn't work.
I'm using the file I sent you and the Wink 2504 version.
I launch Edge, Firefox and Chrome.

Only Firefox stops as expected on frame 55.
Edge and Chrome stop afterwards, probably on the next frame.

Maybe the problem is related: Firefox is very slow to execute the mp4 (slower than other browsers)) but it stops in time!

**Comment by satishsampath** [comment]
The project you linked above has height of 769 pixels. Wink gives me an error asking to Resize All Frames to an even number. Is this something you have resized before rendering on your side? If you haven't seen this error at all, I would suggest check your Wink version to make sure you are indeed using build 2.504 (you can see the version in the Help > About dialog)

**Comment by vivonslasieste** [comment]
Yes, 
I saw this error and
I resized to 768 pixels before the rendering and 
I checked the version number because I was surprised to still have this error.

**Comment by satishsampath** [comment]
Thanks, I can reproduce it in my machine with your project. I'll work on fixing it.

**Comment by satishsampath** [comment]
Fix will be available in the next beta build.

**Comment by satishsampath** [comment]
Fixed in beta build 2.505. Please check and if the issue still exists, reopen this issue.
