### ISSUE TITLE
Rendering MP4 is not possible

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-issues#8]
When I click on the Render button I get a message that I am advised to install FFmpeg. Folowing the links sugested I reach a page that shows the folowing warning message: "ffmpeg.zeranoe.com will close on Sep 18, 2020, and all builds will be removed. If you're using Zeranoe FFmpeg Builds in your product, please ensure that you have a hosting strategy in place by the 18th. Thank you to everyone who supported the project along the way!"

Unless someone wants to take ownership of that project I think it's better to use a different encoder for the next version of Wink.

Since you give us a choice I decided not to install the FFmpeg encoder and "Render without FFmpeg" resulting in the folowing error messages:
![Output settings](https://user-images.githubusercontent.com/53835804/91967217-3524ff00-ed13-11ea-8037-4f0dc0630816.png)
![Error generating output](https://user-images.githubusercontent.com/53835804/91967220-35bd9580-ed13-11ea-9359-0da8e2570fcc.png)
![Error generating output 2](https://user-images.githubusercontent.com/53835804/91967219-35bd9580-ed13-11ea-89d8-cc765e02598c.png)

**Comment by svatas** [comment]
Kind of this error was in build 2.500. Are you sure you are using 2.501 and higher? This bug was [Issue 1](https://github.com/satishsampath/wink-issues/issues/1).

**Comment by satishsampath** [comment]
Can you also try adding a ".mp4" extension to the "Output File Name" field in the Project Settings dialog?

**Comment by satishsampath** [comment]
I can confirm that this happens if you don't have a ".mp4" extension to the output file. I'll check and add that extension during render.

**Comment by dark-passages** [comment]
> Kind of this error was in build 2.500. Are you sure you are using 2.501 and higher? This bug was [Issue 1](https://github.com/satishsampath/wink-issues/issues/1).

Yes I'm sure, and yes I checked, the error code is different.

**Comment by dark-passages** [comment]
Works now!
