### ISSUE TITLE
Feature request: Bigger handles please

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-issues#9]
It could be because of the high resolution on my laptop screen, but the resize handles on the objects are very small. That makes is hard to grab them with the mouse.

![Handles](https://user-images.githubusercontent.com/53835804/91967961-40c4f580-ed14-11ea-9956-92b226bac524.png)

Is it possible to make the handles bigger?

**Comment by satishsampath** [comment]
Sure, I'll make them slightly larger and also adapt to the DPI/scaling setting.

**Comment by dark-passages** [comment]
Perfect, this is a lot easier to manipulate.
Thanks!
